### ISSUE TITLE
Implement more traditional slide-out menu system

### ISSUE THREAD

**Issue by sangyum** [SanDiegoWebDevBootCamp/sangstagram-web#18]
https://material-ui.com/components/drawers/

**Comment by sangyum** [comment]
some sort of left-nav

**Comment by tjdalsans** [comment]
Removing the top nav button and replacing it by implementing a slide out menu system by applying a "persistent drawer". The top nav will instead have a header of the current page that the user will be on.
The drawer will contain Home (Posts), Following (Following), and Profile (Profile) buttons.

**Comment by sangyum** [comment]
This is done with https://github.com/SanDiegoWebDevBootCamp/sangstagram-web/pull/39
