### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by tjdalsans** [SanDiegoWebDevBootCamp/sangstagram-web#22]
adding icons next to the reactions could make the website more attractive.

**Comment by byum1996** [comment]
![Uploading Screen Shot 2019-12-18 at 8.47.43 PM.png…]()

**Comment by minybrandon** [comment]
<img width="471" alt="Screen Shot 2019-12-18 at 8 47 43 PM" src="https://user-images.githubusercontent.com/29720995/71145893-fe847400-21d7-11ea-923b-cc4038357952.png">
